# Generated by Django 3.0.4 on 2020-05-24 07:31

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=smartfields.fields.ImageField(blank=True, upload_to='subcategory'),
        ),
    ]
