# Generated by Django 3.0.4 on 2020-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_categories', '0002_auto_20200524_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='seasons',
            field=models.IntegerField(default=1),
        ),
    ]
