# Generated by Django 3.0.4 on 2020-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='season',
            field=models.IntegerField(default='1'),
        ),
    ]
