# Generated by Django 3.0.4 on 2020-05-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='category')),
                ('description', models.TextField(blank=True)),
                ('typ', models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Comedy', 'Comedy')], default='Comedy', max_length=100)),
            ],
        ),
    ]
