# Generated by Django 3.0.4 on 2020-05-24 07:28

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20200524_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=smartfields.fields.ImageField(blank=True, upload_to='category'),
        ),
    ]
