# Generated by Django 3.0.4 on 2020-05-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20200524_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='typ',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Drama', 'Drama')], default='Comedy', max_length=100),
        ),
    ]
