# Generated by Django 3.0.4 on 2020-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20200524_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='typ',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy')], default='Comedy', max_length=100),
        ),
    ]
